models_project/model_app/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name = 'model_app'

urlpatterns = [
    # path('create-book/', CreateBook.as_view(), name='create_book'), 
    path('books/', books, name='books'),
    path('get_form/', form_view, name='form_view'), 
    path('welcome/', TemplateView.as_view(template_name='template_view.html'), name='welcome'),
    path('bloggers/', BookList.as_view(), name='bloggers'),
    path('blogger/<int:pk>/', BloggerDetail.as_view(), name='blogger'),
    path('create-blogger/', CreateBlogger.as_view(), name="create-blogger"),
    path('update-blogger/<int:pk>/', UpdateBlogger.as_view(), name="update-blogger"),
    path('delete-blogger/<int:pk>/', DeleteBlogger.as_view(), name="delete-blogger"),
    path('form-book/', BookMyFormView.as_view(), name="form-blogger"),
]

models_project/models_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('admin/', admin.site.urls),
    path('', include('model_app.urls', namespace='core_app')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

models_project/model_app/models.py
from django.db import models
from .file_folders import *
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
# Create your models here.
User = get_user_model()

GENDERS = (
    ('k', "Kisi"),
    ('q', "Qadin"),
)

class Blogger(models.Model):
    name = models.CharField("Video bloggerin adi", help_text="Adinizi daxil edin", max_length=50)
    nickname = models.CharField("Nickname", max_length=20)
    avatar = models.ImageField(upload_to="blogger")
    gender = models.CharField('Cinsi', choices=GENDERS, max_length=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Blogger"
        verbose_name_plural = "Bloggerler siyahisi"
        ordering = ("-nickname",)
        db_table = "bloggerler_siyahisi"

    def __str__(self):
        return self.name

    def get_videos(self):
        return self.blogger_videos.all()
    
    def get_absolute_url(self):
        return reverse_lazy('model_app:blogger', kwargs={'pk':self.pk})
  

class Video(models.Model):
    title = models.CharField('Videonun basligi', help_text="Videonun basligi buraya yazilmalidir...", max_length=20)
    description = models.TextField('Text field', blank=True)
    blogger = models.ForeignKey(Blogger, related_name="blogger_videos", on_delete=models.CASCADE)
    video_path = models.FileField(upload_to="video_files/", blank=True)
    cover = models.ImageField(upload_to="video_images/", blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Video"
        verbose_name_plural = "Videolar"
        ordering = ['-created_at']

class Category(models.Model):
    title = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title

class Author(models.Model):
    full_name = models.CharField('Full Adı', max_length=50)
    image = models.ImageField(upload_to='authors/',)
    gender = models.CharField('Cinsi', choices=GENDERS, max_length=1)
    date_of_birthday = models.DateField()
    nationality = models.CharField('Milliyeti', max_length=30)
    info = models.TextField('Yazici haqqinda')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Yazici"
        verbose_name_plural = "Yazicilar"

    def __str__(self):
        return self.full_name


class Book(models.Model):
    title = models.CharField(verbose_name="Kitabin Başlığı", max_length=255)
    description = models.TextField('Məzmun')
    author = models.ForeignKey(to=Author, related_name="author_books", verbose_name="Muellif", on_delete=models.CASCADE)
    price = models.DecimalField(verbose_name='Qiymet', max_digits=5, decimal_places=2)
    page_count = models.IntegerField('Sehife sayi')
    cover_image = models.ImageField('Cover sekili', upload_to=book_image_folder)
    categories = models.ManyToManyField(Category, )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Kitab"
        verbose_name_plural = "Kitablar"
        ordering = 'page_count',

    def __str__(self):
        return self.title  

class Contact(models.Model):
    full_name = models.CharField('ad, Soyad', max_length=40)
    subject = models.CharField('Movzu', max_length=255)
    content = models.TextField('Mezmun',)
    email = models.EmailField(verbose_name="E poct", max_length=20, )

    def __str__(self):
        return '{:s} {:s}'.format(self.subject, self.email)


class Comment(models.Model):
    content = models.TextField('context')
    user = models.ForeignKey(User, related_name="comments", on_delete=models.CASCADE)
    blogger = models.ForeignKey(Blogger, related_name='commets', on_delete=models.CASCADE)

    def __str__(self):
        return self.content

        

models_project/model_app/forms.py
from django import forms
from .validators.form_validators import *
from .models import Book, Comment

class BookForm(forms.ModelForm):
    title = forms.CharField(max_length=20, label="Kitabin Basligi", widget=forms.TextInput(attrs={
        'class':'form-control'
    }))
    class Meta:
        model = Book
        fields = '__all__'

    # def save(self):
    #     instance = super().save(commit=False)
    #     instance.title = instance.title.capitalize()
    #     instance.price = instance.price + (instance.price *10)/100
    #     instance.save()
    #     return instance

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]

models_project/model_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .models import *
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, FormView
from django.views.generic.edit import FormMixin
from django.core.paginator import Paginator
from .forms import BookForm, CommentForm
# Create your views here.

# class CreateBook(CreateView):
#     model = Book
#     template_name = 'book_form.html'
#     success_url = reverse_lazy('core_app:create_book') # returned /create-book/

from django.db.models import Q, F
def books(request):
    book_list = Book.objects.filter(Q(page_count__lt=500) | Q(price__lt=F('page_count')/100))
    print(book_list.query)
    paginator = Paginator(book_list, 2) 
    page = request.GET.get('page', 1)
    books = paginator.get_page(page)
    print(books)
    context = {
        'books':books,
    }
    return render(request, 'books.html', context)

def form_view(request):
    form = BookForm()
    context = {}
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    context['myform']= form
    return render(request, 'form_example.html', context)

class BookList(ListView):
    model = Blogger
    template_name = 'listview.html'
    context_object_name = 'kitablar'
    paginate_by = 5

    # def get_queryset(self):
    #     return Book.objects.values('title')

class BloggerDetail(FormMixin, DetailView):
    model = Blogger
    form_class = CommentForm
    template_name = 'blogger_detail.html'
    context_object_name = 'person'

    def get_success_url(self):
        return reverse_lazy('model_app:blogger', kwargs={'pk': self.object.pk})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return super().form_invalid(form)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.user = self.request.user
        comment.blogger = self.object
        comment.save()
        return super().form_valid(form)


class CreateBlogger(CreateView):
    model = Blogger
    template_name = 'blogger_create.html'
    fields = '__all__'

class UpdateBlogger(UpdateView):
    model = Blogger
    template_name = 'blogger_create.html'
    fields = '__all__'


class DeleteBlogger(DeleteView):
    model = Blogger
    template_name = 'delete_blogger.html'
    success_url = reverse_lazy('model_app:bloggers')

class BookMyFormView(FormView):
    form_class = BookForm
    template_name = 'book_my_form.html'
    success_url = reverse_lazy('model_app:bloggers')


    

models_project/model_app/templates/blogger_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Yarat</button>
    </form>
</body>
</html>

models_project/model_app/templates/blogger_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    name: {{ object.name }}
    nickname: {{ person.nickname }}
    <img src="{{ person.avatar.url }}" alt="">

    <a href="{% url 'model_app:update-blogger' person.id %}">update</a>
    <a href="{% url 'model_app:delete-blogger' person.id %}">delete</a>

    {% for video in person.get_videos %}

    video {{forloop.counter}}: {{video.title}}
    {% endfor %}
    

    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Yarat">
    </form>
</body>
</html>

models_project/model_app/templates/book_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Yarat">
    </form>
</body>
</html>

models_project/model_app/templates/book_my_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Yarat</button>
    </form>
</body>
</html>

models_project/model_app/templates/books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <input type="text">
    {% for book in books %}
        {{ book.title|upper }}<br>
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            <!-- {% if books.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ books.previous_page_number }}">previous</a>
            {% endif %} -->
            {% for number in books.paginator.page_range %}
            {% if books.number is number %}
                {{ number }}
                {% else %}
                <a href="?page={{ number }}">{{ number }}</a>
            {% endif %}

            {% endfor %}
            <!-- <span class="current">
                Page  of {{ books.paginator.num_pages }}.
            </span> -->
    
            <!-- {% if books.has_next %}
                <a href="?page={{ books.next_page_number }}">next</a>
                <a href="?page={{ books.paginator.num_pages }}">last &raquo;</a>
            {% endif %} -->
        </span>
    </div>
</body>
</html>

models_project/model_app/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>{{ad}}</h1>
</body>
</html>

models_project/model_app/templates/delete_blogger.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        {{object}} silmek isteyirsiniz?
        <button type="submit">Sil</button>
        <a href="{{ object.get_absolute_url }}">Xeyr</a>
    </form>
</body>
</html>

models_project/model_app/templates/form_example.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <p>{{message}}</p>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            {% for field in myform %}
                <div class="col-md-6">
                    {% if field.errors %}
                    <div class="alert alert-danger" role="alert">
                            {{field.errors}} 
                          </div>
                    {% endif %}
                    {{field.label_tag}}
                    {{field}}
                </div>
            {% endfor %}
        </div>
        <button type="submit">Gonder</button>
    </form>
</div>

</body>
</html>

models_project/model_app/templates/listview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <ul>
        {% for blogger in kitablar %}
            <li><a href="{{ blogger.get_absolute_url }}">{{ blogger.name }}</a></li>
        {% endfor %}
    </ul>

    <div class="pagination">
            <span class="step-links">
                <!-- {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %} -->
        
                <!-- <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span> -->
                <!-- {% for page_num in page_obj.paginator.page_range %}
                    {% if page_num is page_obj.number %}
                    {{page_num}}
                    {% else %}
                    <a href="?page={{page_num}}">{{page_num}}</a>
                    {% endif %}
                {% endfor %} -->
            
                <!-- {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %} -->
            </span>
        </div>
</body>
</html>

models_project/model_app/templates/template_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Saytimiza xos gelmisiniz!!</h1>
</body>
</html>